# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clock_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(312, 154)
        Form.setMinimumSize(QtCore.QSize(312, 154))
        Form.setMaximumSize(QtCore.QSize(312, 154))
        self.timeDisplay = QtWidgets.QTextEdit(Form)
        self.timeDisplay.setEnabled(True)
        self.timeDisplay.setGeometry(QtCore.QRect(10, 40, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeDisplay.setFont(font)
        self.timeDisplay.setReadOnly(True)
        self.timeDisplay.setObjectName("timeDisplay")
        self.buttonConnect = QtWidgets.QPushButton(Form)
        self.buttonConnect.setEnabled(False)
        self.buttonConnect.setGeometry(QtCore.QRect(230, 70, 71, 23))
        self.buttonConnect.setObjectName("buttonConnect")
        self.buttonHourUp = QtWidgets.QPushButton(Form)
        self.buttonHourUp.setGeometry(QtCore.QRect(20, 10, 51, 23))
        self.buttonHourUp.setObjectName("buttonHourUp")
        self.buttonMinuteUp = QtWidgets.QPushButton(Form)
        self.buttonMinuteUp.setGeometry(QtCore.QRect(90, 10, 51, 23))
        self.buttonMinuteUp.setObjectName("buttonMinuteUp")
        self.buttonSecondUp = QtWidgets.QPushButton(Form)
        self.buttonSecondUp.setGeometry(QtCore.QRect(160, 10, 51, 23))
        self.buttonSecondUp.setObjectName("buttonSecondUp")
        self.buttonSecondDown = QtWidgets.QPushButton(Form)
        self.buttonSecondDown.setGeometry(QtCore.QRect(160, 120, 51, 23))
        self.buttonSecondDown.setObjectName("buttonSecondDown")
        self.buttonHourDown = QtWidgets.QPushButton(Form)
        self.buttonHourDown.setGeometry(QtCore.QRect(20, 120, 51, 23))
        self.buttonHourDown.setObjectName("buttonHourDown")
        self.buttonMinuteDown = QtWidgets.QPushButton(Form)
        self.buttonMinuteDown.setGeometry(QtCore.QRect(90, 120, 51, 23))
        self.buttonMinuteDown.setObjectName("buttonMinuteDown")
        self.comPortBox = QtWidgets.QComboBox(Form)
        self.comPortBox.setGeometry(QtCore.QRect(230, 40, 69, 22))
        self.comPortBox.setObjectName("comPortBox")
        self.buttonAply = QtWidgets.QPushButton(Form)
        self.buttonAply.setEnabled(False)
        self.buttonAply.setGeometry(QtCore.QRect(230, 120, 75, 23))
        self.buttonAply.setObjectName("buttonAply")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "STM32 Clock"))
        self.timeDisplay.setPlaceholderText(_translate("Form", "12:59:59"))
        self.buttonConnect.setText(_translate("Form", "Connect"))
        self.buttonHourUp.setText(_translate("Form", "up"))
        self.buttonMinuteUp.setText(_translate("Form", "up"))
        self.buttonSecondUp.setText(_translate("Form", "up"))
        self.buttonSecondDown.setText(_translate("Form", "down"))
        self.buttonHourDown.setText(_translate("Form", "down"))
        self.buttonMinuteDown.setText(_translate("Form", "down"))
        self.buttonAply.setText(_translate("Form", "aply"))
